---
group-id: "io.quarkiverse.openapi.generator"
artifact-id: "quarkus-openapi-generator"
versions:
- "2.7.1"
- "2.6.0-lts"
- "2.5.0"
- "2.4.7"
- "2.3.0"
- "2.2.16"
- "2.1.1"
- "2.0.0"
- "1.3.16"
- "1.2.1"
- "1.1.0"
- "1.0.1"
- "0.12.0"
- "0.11.0"
- "0.10.0"
- "0.9.0"
- "0.8.0"
- "0.7.0"
- "0.6.1"
- "0.5.0"
- "0.4.1"
- "0.3.1"
- "0.2.0"
- "0.1.0"
exclude-versions: []
